### PR TITLE
QR Code Generator in PHP

### PR DESCRIPTION
**Pull request by mr-vijaychauhan**
# Description

## QR Code Generator 
Create Dynamic QR Code Generator app using PHP. You can create a QR code with text or a Website URL. I use Library for generating QR Code. QR Code saves into images directory.

## Run Project on localhost
`"http://localhost/hacktoberfest-coer/PHP/QR_Code_Generator/"`

## How Has This Been Tested?
  I  Uploaded a Screenshot of what I did inside this project.

- [ ]  Screenshot of QR code app

screencapture-localhost-hacktoberfest2021-hacktoberfest-coer-PHP-QR-Code-Generator-2021-10-05-07_59_50

### CODE REVIEW

**Comment by nakshatra-garg** [comment]
Are you sure there're 429 files in this project?

**Comment by mr-vijaychauhan** [comment]
Yes because of `phpqrcode` library for generate QR Code inside `phpqrcode folder`

**Comment by nakshatra-garg** [comment]
Improve your README.md file add more details, explain a little about it.
Remove that checkbox and add a list if you want.

**Comment by mr-vijaychauhan** [comment]
Ok i will try my best

**Comment by mr-vijaychauhan** [comment]
Updated README.md file. Please Check!

**Pull request merged**
